[tool.poetry]
name = "dnp"
description = "Менджемент врачей и клиник"
authors = ["Herman Volzhsky <avvewyccstrila@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
Django = ">=5.1.6"
django-ninja = ">=1.6"
python-dotenv = "^1.2.1"
django-celery-beat = "^2.7.0"
redis = "^5.2.1"
celery = {extras = ["redis"], version = "^5.4.0"}
psycopg2-binary = "^2.9.10"
django-ninja-extra = "^0.31.4"
django-ninja-jwt = "^5.4.4"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

