# Generated by Django 5.2.15 on 2026-06-09 14:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Название мед. учреждения')),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Некорректный адрес', regex='^[а-яА-ЯёЁ0-9\\s.,\\-]+$')], verbose_name='Адрес учреждения')),
                ('start_work_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало времени работы учреждения')),
                ('end_work_time', models.TimeField(default=datetime.time(23, 59), verbose_name='Конец времени рабочего дня')),
                ('procedures', models.ManyToManyField(null=True, related_name='facilities', to='procedure.procedure')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'db_table': 'facility',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'address'), name='unique_facility_name_address')],
            },
        ),
    ]
