# Generated by Django 5.2.15 on 2026-06-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        ('procedure', '0002_procedure_unique_procedure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='procedures',
            field=models.ManyToManyField(related_name='facilities', to='procedure.procedure'),
        ),
    ]
