# Generated by Django 5.2.15 on 2026-06-09 14:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя врача')),
                ('speciality', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Специальность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('start_work_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Начало времени работы учреждения')),
                ('end_work_time', models.TimeField(default=datetime.time(23, 59), verbose_name='Конец времени рабочего дня')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='facility.facility', verbose_name='Учреждение работы')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'db_table': 'doctor',
                'ordering': ['created_at'],
            },
        ),
    ]
