# Generated by Django 5.2.15 on 2026-06-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('facility', '0002_alter_facility_procedures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='facility.facility', verbose_name='Учреждение работы'),
        ),
    ]
