# Generated by Django 5.2.15 on 2026-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_facility'),
        ('facility', '0002_alter_facility_procedures'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('name', 'speciality'), name='unique_doctor_name_speciality'),
        ),
    ]
