# Generated by Django 5.1.6 on 2026-05-11 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='[а-яА-ЯёЁ]')], verbose_name='Название мед. учреждения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес учреждения')),
                ('start_work_time', models.TimeField(default='08:00', verbose_name='Начало времени работы учреждения')),
                ('end_work_time', models.TimeField(default='17:00', verbose_name='Конец времени рабочего дня')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'db_table': 'facility',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='[а-яА-ЯёЁ]')], verbose_name='Имя процедуры')),
                ('type', models.CharField(choices=[('blood', 'Кровь'), ('head', 'Голова')], default='blood', max_length=100, verbose_name='Тип услуги')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'db_table': 'procedure',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='[а-яА-ЯёЁ]')], verbose_name='Имя врача')),
                ('speciality', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='[а-яА-ЯёЁ]')], verbose_name='Специальность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('start_work_time', models.TimeField(default='08:00', verbose_name='Начало времени работы учреждения')),
                ('end_work_time', models.TimeField(default='17:00', verbose_name='Конец времени рабочего дня')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_app.facility', verbose_name='Учреждение работы')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
                'db_table': 'doctor',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='procedures',
            field=models.ManyToManyField(related_name='procedures', to='medical_app.procedure'),
        ),
    ]
