# Generated by Django 5.1.6 on 2026-05-12 21:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_app', '0002_doctor_deleted_at_facility_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['created_at'], 'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['created_at'], 'verbose_name': 'Учреждение', 'verbose_name_plural': 'Учреждения'},
        ),
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['created_at'], 'verbose_name': 'Процедура', 'verbose_name_plural': 'Процедуры'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='end_work_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Конец времени рабочего дня'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='medical_app.facility', verbose_name='Учреждение работы'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя врача'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_work_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало времени работы учреждения'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Некорректный адрес', regex='^[а-яА-ЯёЁ0-9\\s.,\\-]+$')], verbose_name='Адрес учреждения'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='end_work_time',
            field=models.TimeField(default=datetime.time(23, 59), verbose_name='Конец времени рабочего дня'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Название мед. учреждения'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='procedures',
            field=models.ManyToManyField(null=True, related_name='facilities', to='medical_app.procedure'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='start_work_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Начало времени работы учреждения'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя процедуры'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_facility_name_address'),
        ),
    ]
