# Generated by Django 5.2.15 on 2026-06-09 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только кириллицу', regex='^[а-яА-ЯёЁ\\s-]+$')], verbose_name='Имя процедуры')),
                ('type', models.CharField(choices=[('blood', 'Кровь'), ('head', 'Голова')], default='blood', max_length=100, verbose_name='Тип услуги')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
                'db_table': 'procedure',
                'ordering': ['created_at'],
            },
        ),
    ]
