# Generated by Django 5.2.15 on 2026-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_procedure_type'),
        ),
    ]
